# Generated by Django 3.1.4 on 2020-12-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='work_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
