# Generated by Django 3.1.4 on 2020-12-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20201224_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subscribe',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-date_created'],
            },
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['-contact_date'], 'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
    ]
