# Generated by Django 3.1.4 on 2021-01-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20201225_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='work_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
